Write a MATLAB or Python program to recognize the image of digits. The input 
images are five by-five pixel squares, which display five numbers from 1 to 5, as shown in Figure 1.

In [2]:
import numpy as np

In [4]:
def softmax(x):
    """Softmax activation function for multi-class output"""
    ex = np.exp(x - np.max(x))  # Numerical stability improvement
    return ex / np.sum(ex)

def sigmoid(x):
    """Sigmoid activation function for hidden layer"""
    return 1 / (1 + np.exp(-x))

In [6]:
def multi_class(W1, W2, X, D):
    """Train the network for one epoch"""
    alpha = 0.9  # Learning rate
    N = 5  # Number of training samples
    
    for k in range(N):
        # Reshape input and target
        x = X[:, :, k].reshape(25, 1)
        d = D[k, :].reshape(-1, 1)
        
        # Forward pass
        v1 = np.dot(W1, x)
        y1 = sigmoid(v1)
        v = np.dot(W2, y1)
        y = softmax(v)
        
        # Backpropagation
        e = d - y
        delta = e  # Output layer delta (softmax with cross-entropy)
        e1 = np.dot(W2.T, delta)
        delta1 = y1 * (1 - y1) * e1  # Hidden layer delta
        
        # Weight updates
        dW1 = alpha * np.dot(delta1, x.T)
        W1 = W1 + dW1
        dW2 = alpha * np.dot(delta, y1.T)
        W2 = W2 + dW2
    
    return W1, W2

In [8]:
def main():
    # Set random seed for reproducibility
    np.random.seed(3)
    
    # Define input patterns (5x5 images of digits 1-5)
    X = np.zeros((5, 5, 5))
    
    # Digit 1
    X[:, :, 0] = np.array([[0, 1, 1, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 1, 1, 1, 0]])
    
    # Digit 2
    X[:, :, 1] = np.array([[1, 1, 1, 1, 0],
                          [0, 0, 0, 0, 1],
                          [0, 1, 1, 1, 0],
                          [1, 0, 0, 0, 0],
                          [1, 1, 1, 1, 1]])
    
    # Digit 3
    X[:, :, 2] = np.array([[1, 1, 1, 1, 0],
                          [0, 0, 0, 0, 1],
                          [0, 1, 1, 1, 0],
                          [0, 0, 0, 0, 1],
                          [1, 1, 1, 1, 0]])
    
    # Digit 4
    X[:, :, 3] = np.array([[0, 0, 0, 1, 0],
                          [0, 0, 1, 1, 0],
                          [0, 1, 0, 1, 0],
                          [1, 1, 1, 1, 1],
                          [0, 0, 0, 1, 0]])
    
    # Digit 5
    X[:, :, 4] = np.array([[1, 1, 1, 1, 1],
                          [1, 0, 0, 0, 0],
                          [1, 1, 1, 1, 0],
                          [0, 0, 0, 0, 1],
                          [1, 1, 1, 1, 0]])
    
    # One-hot encoded target labels
    D = np.eye(5)
    
    # Initialize weights randomly
    W1 = 2 * np.random.rand(50, 25) - 1  # Input to hidden (50 hidden units)
    W2 = 2 * np.random.rand(5, 50) - 1   # Hidden to output (5 classes)
    
    # Training loop
    for epoch in range(10000):
        W1, W2 = multi_class(W1, W2, X, D)
        
        # Print progress every 1000 epochs
        if epoch % 1000 == 0:
            print(f"Training epoch {epoch} completed")
    
    # Test the trained network
    N = 5
    for k in range(N):
        x = X[:, :, k].reshape(25, 1)
        
        # Forward pass
        v1 = np.dot(W1, x)
        y1 = sigmoid(v1)
        v = np.dot(W2, y1)
        y = softmax(v)
        
        # Print results
        print(f"\nOutput for digit {k+1}:")
        print(y)
        print(f"Highest probability at position {k+1}: {y[k][0]:.4f}")
        print("Network prediction:", np.argmax(y) + 1)

In [10]:
if __name__ == "__main__":
    main()

Training epoch 0 completed
Training epoch 1000 completed
Training epoch 2000 completed
Training epoch 3000 completed
Training epoch 4000 completed
Training epoch 5000 completed
Training epoch 6000 completed
Training epoch 7000 completed
Training epoch 8000 completed
Training epoch 9000 completed

Output for digit 1:
[[9.99990560e-01]
 [3.73975045e-06]
 [7.29323123e-07]
 [4.95516529e-06]
 [1.56459758e-08]]
Highest probability at position 1: 1.0000
Network prediction: 1

Output for digit 2:
[[3.81399150e-06]
 [9.99984069e-01]
 [1.07138749e-05]
 [7.38201374e-07]
 [6.65377695e-07]]
Highest probability at position 2: 1.0000
Network prediction: 2

Output for digit 3:
[[2.10669179e-06]
 [9.17015598e-06]
 [9.99972467e-01]
 [2.22084036e-06]
 [1.40352894e-05]]
Highest probability at position 3: 1.0000
Network prediction: 3

Output for digit 4:
[[4.72578106e-06]
 [8.98916172e-07]
 [9.07090140e-07]
 [9.99990801e-01]
 [2.66714208e-06]]
Highest probability at position 4: 1.0000
Network prediction: 4