Consider an artificial neural network (ANN) with three layers given below. Write a
MATLAB or Python program to learn this network using Back Propagation Network.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
class SimpleANN(nn.Module):
    def __init__(self):
        super(SimpleANN, self).__init__()
        # Input to Hidden layer (2 inputs to 2 hidden nodes)
        self.hidden = nn.Linear(2, 2)  # 2 input neurons, 2 hidden neurons
        # Hidden to Output layer (2 hidden nodes to 2 output nodes)
        self.output = nn.Linear(2, 2)  # 2 hidden neurons, 2 output neurons
        # Sigmoid activation function
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Forward pass through the network
        h = self.sigmoid(self.hidden(x))  # Hidden layer activation
        y = self.sigmoid(self.output(h))  # Output layer activation
        return y

In [3]:
model = SimpleANN()

# Manually set the weights and biases based on the diagram
with torch.no_grad():
    # Hidden layer weights (w1-w4) and bias (b1)
    model.hidden.weight = torch.nn.Parameter(torch.tensor([[0.15, 0.20], [0.25, 0.30]]))
    model.hidden.bias = torch.nn.Parameter(torch.tensor([0.35, 0.35]))

    # Output layer weights (w5-w8) and bias (b2)
    model.output.weight = torch.nn.Parameter(torch.tensor([[0.40, 0.45], [0.50, 0.55]]))
    model.output.bias = torch.nn.Parameter(torch.tensor([0.60, 0.60]))

In [4]:
# Input (x1, x2) and target values (T1, T2)
inputs = torch.tensor([[0.05, 0.10]])  # Single input pair
targets = torch.tensor([[0.01, 0.99]])  # Target values for y1 and y2

# Loss function (Mean Squared Error)
criterion = nn.MSELoss()

# Optimizer (Stochastic Gradient Descent)
optimizer = optim.SGD(model.parameters(), lr=0.5)

# Training epochs
epochs = 15000

In [5]:
print("Starting training...\n")

for epoch in range(epochs):
    # Forward pass
    output = model(inputs)

    # Compute loss
    loss = criterion(output, targets)

    # Backpropagation
    optimizer.zero_grad()  # Clear gradients
    loss.backward()        # Compute gradients
    optimizer.step()       # Update weights

    # Print progress every 1000 epochs
    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d}, Loss: {loss.item():.6f}")

Starting training...

Epoch     0, Loss: 0.298371
Epoch  1000, Loss: 0.000271
Epoch  2000, Loss: 0.000090
Epoch  3000, Loss: 0.000044
Epoch  4000, Loss: 0.000025
Epoch  5000, Loss: 0.000015
Epoch  6000, Loss: 0.000010
Epoch  7000, Loss: 0.000007
Epoch  8000, Loss: 0.000005
Epoch  9000, Loss: 0.000003
Epoch 10000, Loss: 0.000002
Epoch 11000, Loss: 0.000002
Epoch 12000, Loss: 0.000001
Epoch 13000, Loss: 0.000001
Epoch 14000, Loss: 0.000001


In [6]:
print("\nFinal weights and biases:")
for name, param in model.named_parameters():
    print(f"{name}:")
    print(param.data)
    print()

# Final output after training
final_output = model(inputs)
print(f"\nFinal network output:")
print(f"y1: {final_output[0][0]:.4f} (target: 0.01)")
print(f"y2: {final_output[0][1]:.4f} (target: 0.99)")


Final weights and biases:
hidden.weight:
tensor([[0.1833, 0.2667],
        [0.2826, 0.3652]])

hidden.bias:
tensor([1.0170, 1.0025])

output.weight:
tensor([[-1.4728, -1.4261],
        [ 1.5441,  1.5950]])

output.bias:
tensor([-2.3714,  2.1961])


Final network output:
y1: 0.0108 (target: 0.01)
y2: 0.9893 (target: 0.99)
